[package]
name = "smb-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
smb-lib = { path = "../smb-lib" }
clap = { version = "4.5.27", features = ["derive"] }
env_logger = "0.11.6"
log = "0.4.22"