[package]
name = "smb"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.14.1"
rand = "0.8.5"
modular-bitfield = "0.11.2"
gss-api = {version = "0.1.0", features = []}
der = {version = "0.7.9", features = ["std", "alloc"]}
sspi = "0.15.0"
aes-gcm = {version = "0.10.3", features = ["std"]}
rust-kbkdf = {version = "1.0.1"}