services:
  tests:
    build:
      context: crates/smb/tests
      dockerfile: Dockerfile
      tags:
        - ghcr.io/avivnaaman/smb-tests:latest
      platforms:
        - linux/amd64
    ports:
      - 445:445
      - 139:139
    networks:
      - default
      - default2
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    environment:
      ACCOUNT_LocalAdmin: 123456
      SAMBA_CONF_LOG_LEVEL: 10
      SAMBA_VOLUME_CONFIG_MyShare: "[MyShare]; path=/shares/MyShare; read only = no; browseable = yes; create mask = 0777; directory mask = 0777; smb encrypt = desired"
      SAMBA_VOLUME_CONFIG_PublicShare: "[PublicShare]; path=/shares/PublicShare; read only = no; browseable = yes; guest ok = yes; smb encrypt = disabled"
      SAMBA_GLOBAL_CONFIG_smb_SPACE_ports: "139 445"
      SAMBA_GLOBAL_CONFIG_smb_SPACE_encrypt: "auto"
      SAMBA_GLOBAL_CONFIG_server_SPACE_multi_SPACE_channel_SPACE_support: "yes"
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    entrypoint: tail -f /dev/null
    networks:
      - default
      - default2
    volumes: 
      - .:/smb

networks:
  default:
    driver: bridge
  default2:
    driver: bridge