services:
  tests:
    build:
      context: smb/tests
      dockerfile: Dockerfile
      tags:
        - ghcr.io/avivnaaman/smb-tests:latest
      platforms:
        - linux/amd64
    ports:
      - 445:445
      - 139:139
    networks:
      - default
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    environment:
      ACCOUNT_LocalAdmin: 123456
      SAMBA_CONF_LOG_LEVEL: 10
      SAMBA_VOLUME_CONFIG_MyShare: "[MyShare]; path=/shares/MyShare; read only = no; browseable = yes; create mask = 0777; directory mask = 0777"
      SAMBA_GLOBAL_CONFIG_smb_SPACE_ports: "139 445"
  dev:
    image: rust:latest
    environment:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    entrypoint: tail -f /dev/null
    networks:
      - default
    volumes: 
      - .:/smb

networks:
  default:
    driver: bridge