[package]
name = "smb-msg-derive"
description = "Derive macros for smb-msg"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1"
syn = { version = "2", features = ["full"] }

[features]
default = []

both = ["client", "server"]
server = []
client = []
