name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        compile_features: [ async, sync ]

    steps:
    - uses: actions/checkout@v4
    - name: Build/${{ matrix.compile_features }}
      run: cargo build --verbose --features ${{ matrix.compile_features }}
    - name: Tests/${{ matrix.compile_features }}
      run: cargo test --verbose --features ${{ matrix.compile_features }}
